# Generated by Django 4.1.7 on 2023-02-19 19:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('realtors', '0003_rename_name_realtor_first_name_remove_realtor_photo_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Realty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('bedrooms', models.IntegerField(default=0)),
                ('bathrooms', models.IntegerField(default=0)),
                ('sqft', models.IntegerField()),
                ('garage', models.IntegerField(default=0)),
                ('floor', models.IntegerField(default=1)),
                ('price', models.DecimalField(decimal_places=10, max_digits=11)),
                ('realtor', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='realtors.realtor')),
            ],
        ),
    ]
