# Generated by Django 4.1.7 on 2023-02-19 20:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('realty', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='realty',
            old_name='realtor',
            new_name='realtor_id',
        ),
    ]
