# Generated by Django 4.1.7 on 2023-02-19 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('realty', '0002_rename_realtor_realty_realtor_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='realty',
            name='price',
            field=models.DecimalField(decimal_places=1, max_digits=11),
        ),
    ]
